version: "3.8"

services:
  mysql_source:
    image: mysql:8.0.32
    container_name: mysql_source
    hostname: mysql_source
    restart: always

    networks:
      - default
      - phpmyadmin
      - metabase

    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --disable-log-bin

    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "RootPassword"
      MYSQL_DATABASE: "suitecrm"
      MYSQL_USER: "suitecrm"
      MYSQL_PASSWORD: "UserPassword"

    logging:
      options:
        max-size: "10m"
        max-file: "3"

    volumes:
      # Define Time and Timezone
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

      # Data Storage
      - ./data/mysql:/var/lib/mysql

      # Configuration
      - ./config/source.cnf:/etc/mysql/conf.d/source.cnf:ro

    labels:
      traefik.enable: false

  # -------------------------------------------

  mysql_replica:
    image: mysql:8.0.32
    container_name: mysql_replica
    hostname: mysql_replica
    restart: always

    networks:
      - default
      - phpmyadmin
      - metabase

    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --disable-log-bin

    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "RootPassword"
      MYSQL_DATABASE: "suitecrm"
      MYSQL_USER: "suitecrm"
      MYSQL_PASSWORD: "UserPassword"

    logging:
      options:
        max-size: "10m"
        max-file: "3"

    volumes:
      # Define Time and Timezone
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

      # Data Storage
      - ./data/mysql:/var/lib/mysql

      # Configuration
      - ./config/replica.cnf:/etc/mysql/conf.d/replica.cnf:ro

    labels:
      traefik.enable: false

  # -------------------------------------------

networks:
  phpmyadmin:
    name: phpmyadmin_default
  metabase:
    name: metabase_default
